applenews.applenews_template.*:
  type: config_entity
  label: 'Apple News Template'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    node_type:
      type: string
      label: 'Node type'
    view_mode:
      type: string
      label: 'View mode'
    columns:
      type: integer
      label: 'Columns'
    width:
      type: integer
      label: 'Width'
    margin:
      type: integer
      label: 'Margin'
    gutter:
      type: integer
      label: 'Gutter'
    components:
      type: sequence
      sequence:
        type: applenews.applenews_component.[%key]

applenews.applenews_component.*:
  type: config_object
  mapping:
    uuid:
      type: string
    id:
      type: string
      label: 'Plugin ID'
    component_type:
      type: string
    weight:
      type: integer
      label: 'Weight'
    component_layout:
      type: applenews.component_layout
    component_data:
      type: applenews.component_type.[%parent.component_type]

applenews.component_type.text:
  type: mapping
  mapping:
    text_field:
      type: string
      label: 'Source field for text'

applenews.component_type.image:
  type: mapping
  mapping:
    url_field:
      type: string
      label: 'Source field'
    caption_field:
      type: string
      label: 'Source field for caption'

applenews.component_layout:
  type: mapping
  mapping:
    column_start:
      type: integer
    column_span:
      type: integer

