applenews.applenews_template.*:
  type: config_entity
  label: 'Apple News Template'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    node_type:
      type: string
      label: 'Node type'
    view_mode:
      type: string
      label: 'View mode'
    columns:
      type: integer
      label: 'Columns'
    width:
      type: integer
      label: 'Width'
    margin:
      type: integer
      label: 'Margin'
    gutter:
      type: integer
      label: 'Gutter'
    components:
      type: sequence
      sequence:
        type: applenews.applenews_component_type.[%key]

applenews.applenews_component_type.*:
  type: config_object
  mapping:
    component_type:
      type: string
      label: 'Component Type'
    weight:
      type: integer
      label: 'Weight'
    field_name:
      type: string
      label: 'Field'
    component_layout:
      type: mapping
      mapping:
        column_start:
          type: integer
        column_span:
          type: integer
    components:
      type: sequence
      sequence:
        type: applenews.applenews_component_type.[%key]
